require "rspec"

require_relative "area_data_spec"
require_relative "area_header_spec"
require_relative "helps_spec"
require_relative "mobiles_spec"
require_relative "objects_spec"
require_relative "rooms_spec"
require_relative "resets_spec"
require_relative "shops_spec"
require_relative "specials_spec"
