# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

require_relative "area_header_spec"
require_relative "area_data_spec"
require_relative "helps_spec"
require_relative "mobiles_spec"
require_relative "objects_spec"
require_relative "rooms_spec"
require_relative "resets_spec"
require_relative "shops_spec"
require_relative "specials_spec"
